config/routes.rb
BowlingCharts::Application.routes.draw do
  resources :bowling
  post 'bowling/frame', to: 'bowling#frame'
  root 'bowling#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bowling.rb
class Bowling < ApplicationRecord
  attr_reader :error_message, :frame_number, :frame, :try1, :try2

  FRAMES = 10
  PINS   = 10

  def initialize(params, frame)
    @frame = frame.nil? ? [nil] : frame
    @try1 = params[:try1].to_i if params[:try1]
    @try2 = params[:try2].to_i if params[:try2]
    frame_number
  end

  def frame_number
    @frame_number ||= valid? ? frame.size : frame.size - 1
  end

  def calculate
    @frame[frame_number] = {spare: spare?, strike: strike?, score: calc_frame_score, try1: @try1, try2: @try2}
  end

  def total
    @frame.inject(0){|rez, item| item ? rez + item[:score] : rez }
  end

  def over?
    frame_number >= FRAMES + (frame_number == FRAMES && (strike? || spare?)  ? 1 : 0)
  end

  def strike?
    @try1 == PINS
  end

  def spare?
    @try1 + @try2 == PINS
  end

  def valid?
    @valid ||= begin
      @error_message = ''
      if !@try1 || !check_range(@try1)
        @error_message = 'Wrong input of pins: try 1'
        return
      end

      if (!strike? && !@try2) || !check_range(@try2)
        @error_message = 'Wrong input of pins : try 2'
        return
      end
      if !strike? && !check_range(@try1 + @try2)
        @error_message = 'Wrong sum of pins'
        return
      end
      true
    end
  end

  private

  def calc_frame_score
    prev_frame = frame[frame_number - 1]
    if prev_frame && (prev_frame[:strike] || prev_frame[:spare])
      frame[frame_number - 1][:score] = PINS + @try1 + (prev_frame[:strike] ? @try2 : 0)
    end
    @try1 + @try2
  end

  def check_range(num)
    (0..PINS) === num
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bowling_controller.rb
class BowlingController < ApplicationController

  def frame
    @game = Bowling.new(bowl_params, session[:frame])
    if @game.valid?
      @game.calculate
    else
      flash[:error] = @game.error_message
    end
    session[:frame] = @game.over? ? nil : @game.frame
  end

  def new
    session[:frame] = nil
    redirect_to '/bowling'
  end

  private

  def bowl_params
    params.permit(:try1, :try2, :frame_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/bowling_helper.rb
module BowlingHelper

  def score_cells
    scores = ''
    @game.frame.each{|frame| scores += "<td>#{frame[:score]}</td>" if frame}
    scores
  end

  def try1_cells
    try1 = ''
    @game.frame.each{|frame| try1 += "<td>#{frame[:try1]}</td>" if frame}
    try1
  end

  def try2_cells
    try2 = ''
    @game.frame.each{|frame| try2 += "<td>#{frame[:try2]}</td>" if frame}
    try2
  end

  def frame_cells
    header = ''
    (1..@game.frame_number).each{|frame| header += "<td>##{frame}</td>"}
    header
  end
end

app/views/bowling/_form.html.erb
<div class="jumbotron">
  <%= form_tag bowling_frame_path, class: 'form-horizontal' do %>
    <label><b>Enter the Pins knocked:</b></label><p>
    <div id="pins_form">
      <%= hidden_field_tag :frame_number, @game.frame_number if @game%>
      <div class="form-group" id="try1-block">
        <div class="row">
          <%= label_tag(:try1, 'Try1',  class: 'control-label') %>
          <div class="col-sm-10">
            <%= text_field_tag :try1, 0, size: 3, maxlength: 2 %>
          </div>
        </div>
      </div>
        <br />
      <div class="form-group" id="try2-block">
        <div class="row">
          <%= label_tag(:try2, 'Try2', class: 'control-label') %>
          <div class="col-sm-10">
            <%= text_field_tag :try2, 0, size: 3, maxlength: 2 %><br />
          </div>
        </div>
      </div>
    </div>

    <br />
    <%= submit_tag 'Submit Frame'%>
  <% end %>
</div>

app/views/bowling/_results.html.erb
<div class="jumbotron">
  <table class="table table-striped table-bordered table-dark table-hover" id="results" >
    <tr>
      <td class="frame_cols">Frame:</td>
      <%== frame_cells %>
      <td>
        Final Score
      </td>
    </tr>
    <tr>
      <td class="try1_cols">
        try1:
      <%== try1_cells %>
      </td>
    </tr>
    <tr>
      <td class="try2_cols">
        try2: <%== try2_cells %>
      </td>
    </tr>
    <tr>
      <td class="Score_cols">Score:</td>
      <%== score_cells%>
      <td class="total">
        <%= @game.total %>
      </td>
    </tr>
  </table>
</div>

app/views/bowling/frame.html.erb
<h2><a class="btn btn-dark btn-primary" href="/bowling/new">New Game</a></h2>

<%= render 'results' %>
<%= render 'form' if !@game.over? %>

app/views/bowling/index.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BowlingCharts</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="content">
  <% flash.each do |key, value| %>
    <div class="jumbotron" >
      <div class ="row">
        <div class="span8">
          <div class ="flash-message" id= "<%=key %>"><%= value %></div>
        </div>
      </div>
    </div>
  <% end if @game && !@game.error_message.empty? %>

<%= yield %>
</div>

</body>
</html>